logger:
  level: 'DEBUG'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
listener:
  read_size: 10240
  delay: 0.0
  host: '127.0.0.1'
  ports:
    - 21
    - 22
    - 23
    - 25
    - 53
    - 80
    - 110
    - 111
    - 135
    - 139
    - 143
    - 443
    - 445
    - 993
    - 995
    - 1723
    - 3306
    - 3389
    - 5900
    - 8080
collector:
  type: 'csv'  # available options: 'stdout', 'csv'
  csv:
    filename: 'data.csv'
  stdout:
    # no additional configuration
